# Generated by Django 4.0.1 on 2022-01-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(blank=True, max_length=15, null=True)),
                ('affiliation', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
